export const SUPPORTED_LOCALES = ['fr', 'en', 'es', 'de', 'it'] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];
export type LanguagePreference = SupportedLocale | 'system';

const fr = {
  'language.system': 'Langue du système', 'language.fr': 'Français', 'language.en': 'English', 'language.es': 'Español', 'language.de': 'Deutsch', 'language.it': 'Italiano',
  'common.cancel': 'Annuler', 'common.save': 'Enregistrer', 'common.saving': 'Enregistrement…', 'common.close': 'Fermer', 'common.delete': 'Supprimer', 'common.edit': 'Modifier', 'common.loading': 'Chargement…', 'common.confirm': 'Confirmer', 'common.back': 'Retour', 'common.send': 'Envoyer', 'common.copy': 'Copier', 'common.download': 'Télécharger', 'common.installRestart': 'Installer et redémarrer', 'common.later': 'Plus tard', 'common.none': '—',
  'nav.calendar': 'Calendrier', 'nav.newPublication': 'Nouvelle publication', 'nav.accounts': 'Comptes', 'nav.history': 'Historique', 'nav.settings': 'Paramètres', 'nav.feedback': 'Suggestion / Correction', 'nav.about': 'À propos',
  'calendar.title': 'Calendrier', 'calendar.subtitle': "Vue d’ensemble de vos publications planifiées.", 'calendar.previous': 'Précédent', 'calendar.next': 'Suivant', 'calendar.today': "Aujourd’hui", 'calendar.month': 'Mois', 'calendar.week': 'Semaine', 'calendar.weekOf': 'Semaine du {{date}}',
  'accounts.title': 'Comptes', 'accounts.subtitle': 'Gérez vos profils TikTok pour organiser vos publications.', 'accounts.new': 'Nouveau compte', 'accounts.loading': 'Chargement des comptes…', 'accounts.empty': 'Aucun compte pour le moment. Créez votre premier compte pour commencer à planifier.', 'accounts.editTitle': 'Modifier le compte', 'accounts.newTitle': 'Nouveau compte', 'accounts.name': 'Nom du compte', 'accounts.namePlaceholder': 'Ex. Compte principal', 'accounts.handle': 'Pseudo TikTok', 'accounts.handlePlaceholder': '@monpseudo', 'accounts.color': 'Couleur', 'accounts.chooseColor': 'Choisir la couleur {{color}}', 'accounts.count': '{{count}} publication(s)', 'accounts.required': 'Le nom et le pseudo TikTok sont obligatoires.', 'accounts.deleteTitle': 'Supprimer le compte', 'accounts.deleteWithPublications': 'Ce compte a {{count}} publication(s) associée(s). Elles seront également supprimées. Continuer ?', 'accounts.deleteConfirm': 'Voulez-vous vraiment supprimer le compte « {{name}} » ?',
  'history.title': 'Historique', 'history.subtitle': 'Retrouvez toutes vos publications passées.', 'history.allAccounts': 'Tous les comptes', 'history.status': 'Statut', 'history.defaultStatuses': 'Publié / Manqué / Annulé', 'history.from': 'Du', 'history.to': 'Au', 'history.empty': 'Aucune publication ne correspond à ces filtres.', 'history.titleColumn': 'Titre', 'history.type': 'Type', 'history.scheduledDate': 'Date planifiée', 'history.publishedDate': 'Date publiée',
  'settings.title': 'Paramètres', 'settings.subtitle': "Personnalisez les rappels et le comportement de l’application.", 'settings.language': 'Langue', 'settings.languageHint': 'Appliquée immédiatement à toute l’application.', 'settings.reminderLead': 'Délai de rappel par défaut (minutes avant la publication)', 'settings.reminderHint': "Utilisé quand aucun rappel personnalisé n’est défini sur une publication.", 'settings.notifications': 'Activer les notifications', 'settings.preReminder': "Envoyer un rappel avant l’heure planifiée", 'settings.launchMinimized': 'Démarrer réduit dans la barre des tâches', 'settings.startOnLogin': 'Démarrer avec le système', 'settings.saved': 'Enregistré ✓', 'settings.save': 'Enregistrer les paramètres', 'settings.updates': 'Mises à jour', 'settings.installedVersion': 'Version installée : {{version}}', 'settings.checkUpdate': 'Rechercher une mise à jour', 'settings.devUnavailable': 'Recherche indisponible en mode développement (nécessite une version installée).', 'settings.checking': 'Recherche en cours…', 'settings.upToDate': 'TikTok Manager est à jour.', 'settings.available': 'Version {{version}} disponible sur GitHub.', 'settings.downloading': 'Téléchargement en cours…', 'settings.ready': 'Version {{version}} prête. Redémarrage nécessaire pour l’installer.', 'settings.updateError': 'Erreur lors de la vérification.',
  'planning.titleNew': 'Nouvelle publication', 'planning.titleEdit': 'Modifier la publication', 'planning.subtitle': 'Importez une vidéo, complétez les informations et planifiez la date de publication.', 'planning.noAccount': 'Créez d’abord un compte dans la page « Comptes » avant de planifier une publication.', 'planning.goAccounts': 'Aller aux comptes', 'planning.video': 'Vidéo', 'planning.noVideo': 'Aucune vidéo', 'planning.import': 'Importer une vidéo', 'planning.changeVideo': 'Changer la vidéo', 'planning.importing': 'Import en cours…', 'planning.ready': '✓ Vidéo prête à publier', 'planning.checks': '⚠ Vérifications recommandées', 'planning.contentType': 'Type de contenu', 'planning.account': 'Compte', 'planning.title': 'Titre', 'planning.titlePlaceholder': 'Titre de la vidéo', 'planning.description': 'Description / légende', 'planning.descriptionPlaceholder': 'Décrivez votre contenu…', 'planning.assistant': 'Assistant éditorial local', 'planning.suggestHashtags': '+ Hashtags suggérés', 'planning.hashtags': 'Hashtags', 'planning.date': 'Date de publication', 'planning.time': 'Heure de publication', 'planning.customReminder': 'Rappel personnalisé (minutes avant, optionnel)', 'planning.reminderPlaceholder': 'Utiliser le délai par défaut des paramètres', 'planning.cancelPublication': 'Annuler la publication', 'planning.selectAccount': 'Sélectionnez un compte.', 'planning.importRequired': 'Importez une vidéo.', 'planning.titleRequired': 'Le titre est obligatoire.', 'planning.suggestion1': 'Le saviez-vous ? {{title}} — regardez jusqu’à la fin 👀', 'planning.suggestion2': '{{title}} : 3 points à retenir. Le dernier est le plus important.', 'planning.suggestion3': 'J’ai testé {{title}} pour vous. Voici le résultat sans détour.', 'planning.suggestionFallback': 'Voici une astuce', 'planning.suggestionContent': 'Nouveau contenu', 'planning.suggestionMethod': 'cette méthode',
  'preview.title': 'Aperçu de la publication', 'preview.videoUnavailable': 'Vidéo indisponible', 'preview.unknownAccount': 'Compte inconnu', 'preview.description': 'Description', 'preview.noDescription': 'Aucune description.', 'preview.publish': 'Publier sur TikTok', 'preview.markPublished': 'Marquer comme publié', 'preview.cancel': 'Annuler la publication',
  'tag.placeholder': 'Ajouter un hashtag et appuyer sur Entrée', 'tag.remove': 'Retirer {{tag}}', 'thumbnail.unavailable': 'Miniature indisponible',
  'status.scheduled': 'Planifié', 'status.reminderSent': 'Rappel envoyé', 'status.published': 'Publié', 'status.missed': 'Manqué', 'status.cancelled': 'Annulé', 'type.video': 'Vidéo', 'type.story': 'Story',
  'about.title': 'À propos de TikTok Manager', 'about.version': 'Version {{version}}', 'about.description': 'TikTok Manager est une application pour organiser et planifier les vidéos et stories de plusieurs comptes TikTok depuis un calendrier visuel.', 'about.credits': 'Crédits', 'about.design': 'Conception et développement : bob59', 'about.builtWith': 'Construit avec Electron, React et TypeScript.', 'about.footer': 'Créé par bob59 · © 2026',
  'feedback.title': 'Suggestion / Correction', 'feedback.subtitle': 'Une idée ou un problème ? Écrivez-nous.', 'feedback.subject': 'Sujet', 'feedback.message': 'Message', 'feedback.defaultSubject': 'TikTok Manager - Suggestion / Correction', 'feedback.placeholder': 'Décrivez votre suggestion ou les étapes du problème…', 'feedback.copied': 'Adresse et message copiés.', 'feedback.app': 'Application : TikTok Manager', 'feedback.to': 'À',
  'update.title': 'Mise à jour disponible', 'update.versions': 'Version {{available}} — vous utilisez la {{current}}', 'update.downloading': 'Téléchargement en cours…', 'update.calculating': 'calcul…', 'update.remaining': 'Temps restant estimé : {{seconds}} s', 'update.bannerAvailable': 'Mise à jour {{version}} disponible', 'update.bannerReady': 'Mise à jour {{version}} prête à installer', 'update.details': 'Voir les détails',
  'menu.file': 'Fichier', 'menu.quit': 'Quitter', 'menu.edit': 'Édition', 'menu.undo': 'Annuler', 'menu.redo': 'Rétablir', 'menu.cut': 'Couper', 'menu.copy': 'Copier', 'menu.paste': 'Coller', 'menu.delete': 'Supprimer', 'menu.selectAll': 'Tout sélectionner', 'menu.view': 'Affichage', 'menu.reload': 'Recharger', 'menu.forceReload': 'Forcer le rechargement', 'menu.devTools': 'Outils de développement', 'menu.actualSize': 'Taille réelle', 'menu.zoomIn': 'Zoom avant', 'menu.zoomOut': 'Zoom arrière', 'menu.fullscreen': 'Plein écran', 'menu.window': 'Fenêtre', 'menu.minimize': 'Réduire', 'menu.close': 'Fermer', 'menu.help': 'Aide', 'menu.checkUpdate': 'Rechercher une mise à jour', 'tray.open': 'Ouvrir TikTok Manager', 'tray.newPublication': 'Nouvelle publication',
  'notification.reminderTitle': 'Rappel de publication', 'notification.reminderBody': '« {{title}} » est prévu dans {{minutes}} min.', 'notification.dueTitle': "C’est l’heure de publier !", 'notification.dueBody': '« {{title}} » est planifié maintenant.',
  'dialog.importVideo': 'Importer une vidéo', 'dialog.videos': 'Vidéos',
  'validation.required': '{{label}} est obligatoire.', 'validation.tooLong': '{{label}} dépasse {{max}} caractères.', 'validation.invalid': '{{label}} invalide.', 'validation.managedFile': '{{label}} doit être un fichier importé par l’application.', 'validation.name': 'Le nom', 'validation.handle': 'Le pseudo TikTok', 'validation.color': 'Couleur', 'validation.contentType': 'Type de contenu', 'validation.publicationDate': 'Date de publication', 'validation.hashtags': 'Liste de hashtags', 'validation.reminder': 'Le rappel doit être compris entre 0 et 10 080 minutes.', 'validation.video': 'Vidéo', 'validation.thumbnail': 'Miniature', 'validation.description': 'Description', 'validation.title': 'Le titre', 'validation.settings': 'Paramètres invalides.', 'validation.defaultReminder': 'Le délai de rappel est invalide.', 'validation.boolean': 'Paramètre booléen invalide.', 'validation.filters': 'Filtres invalides.', 'validation.filterDate': 'Date de filtre invalide.', 'validation.id': 'Identifiant invalide.', 'validation.dateRange': 'Plage de dates invalide.', 'validation.accountMissing': 'Compte introuvable.', 'validation.publicationMissing': 'Publication introuvable.', 'validation.duplicate': 'Une publication est déjà programmée pour ce compte à cette date et cette heure.', 'validation.duplicateOther': 'Une autre publication utilise déjà ce créneau pour ce compte.', 'validation.fileTooLarge': 'La vidéo dépasse la limite de sécurité de 4 Go.',
  'video.warningVertical': 'La vidéo n’est pas verticale (format 9:16 recommandé).', 'video.warningResolution': 'Résolution faible : 1080 × 1920 est recommandé.', 'video.warningDuration': 'La vidéo dépasse 10 minutes.', 'video.warningAudio': 'Aucune piste audio détectée.', 'video.warningSize': 'Le fichier dépasse 4 Go.', 'update.devError': 'Vérification indisponible en mode développement.', 'validation.language':'Langue invalide.', 'protocol.invalidPath':'Chemin invalide', 'protocol.denied':'Accès refusé', 'store.invalid':'Format de données invalide.', 'store.accountsInvalid':'Liste des comptes invalide.', 'store.publicationsInvalid':'Liste des publications invalide.', 'store.settingsInvalid':'Paramètres invalides.',
  'welcome.title':'Bienvenue sur TikTok Manager', 'welcome.eyebrow':'Bienvenue', 'welcome.headline':'Merci d’utiliser TikTok Manager !', 'welcome.description':'Organisez vos contenus, planifiez vos publications et gérez plusieurs comptes TikTok depuis un calendrier clair.', 'welcome.thanks':'Votre confiance nous aide à faire évoluer cette application gratuite.', 'welcome.support':'Si TikTok Manager vous est utile, vous pouvez soutenir son développement via PayPal.', 'welcome.donate':'Faire un don', 'welcome.later':'Plus tard', 'welcome.dontShow':'Ne plus afficher cette fenêtre au démarrage', 'welcome.closeLabel':'Fermer la fenêtre de bienvenue', 'welcome.openError':'Impossible d’ouvrir la page PayPal.', 'settings.welcomeTitle':'Accueil et soutien', 'settings.welcomeDescription':'Choisissez si la fenêtre de bienvenue doit s’afficher au démarrage.', 'settings.showWelcome':'Afficher la bienvenue au démarrage', 'settings.previewWelcome':'Revoir la fenêtre de bienvenue', 'donation.invalidUrl':'Le lien de don intégré est invalide.'
} as const;

export type TranslationKey = keyof typeof fr;
type Catalog = Record<TranslationKey, string>;

const en: Catalog = Object.fromEntries(Object.keys(fr).map((key) => [key, key])) as Catalog;
const es: Catalog = { ...en };
const de: Catalog = { ...en };
const it: Catalog = { ...en };

// Complete English catalog; the remaining catalogs are filled below with native overrides.
Object.assign(en, { 'language.fr':'Français', 'language.en':'English', 'language.es':'Español', 'language.de':'Deutsch', 'language.it':'Italiano' });
Object.assign(en, {
  'language.system':'System language','common.cancel':'Cancel','common.save':'Save','common.saving':'Saving…','common.close':'Close','common.delete':'Delete','common.edit':'Edit','common.loading':'Loading…','common.confirm':'Confirm','common.back':'Back','common.send':'Send','common.copy':'Copy','common.download':'Download','common.installRestart':'Install and restart','common.later':'Later','common.none':'—',
  'nav.calendar':'Calendar','nav.newPublication':'New publication','nav.accounts':'Accounts','nav.history':'History','nav.settings':'Settings','nav.feedback':'Suggestion / Correction','nav.about':'About',
  'calendar.title':'Calendar','calendar.subtitle':'Overview of your scheduled publications.','calendar.previous':'Previous','calendar.next':'Next','calendar.today':'Today','calendar.month':'Month','calendar.week':'Week','calendar.weekOf':'Week of {{date}}',
  'accounts.title':'Accounts','accounts.subtitle':'Manage your TikTok profiles and organize your publications.','accounts.new':'New account','accounts.loading':'Loading accounts…','accounts.empty':'No accounts yet. Create your first account to start scheduling.','accounts.editTitle':'Edit account','accounts.newTitle':'New account','accounts.name':'Account name','accounts.namePlaceholder':'E.g. Main account','accounts.handle':'TikTok username','accounts.handlePlaceholder':'@myusername','accounts.color':'Color','accounts.chooseColor':'Choose color {{color}}','accounts.count':'{{count}} publication(s)','accounts.required':'The name and TikTok username are required.','accounts.deleteTitle':'Delete account','accounts.deleteWithPublications':'This account has {{count}} associated publication(s). They will also be deleted. Continue?','accounts.deleteConfirm':'Are you sure you want to delete the account “{{name}}”?',
  'history.title':'History','history.subtitle':'Find all your past publications.','history.allAccounts':'All accounts','history.status':'Status','history.defaultStatuses':'Published / Missed / Cancelled','history.from':'From','history.to':'To','history.empty':'No publications match these filters.','history.titleColumn':'Title','history.type':'Type','history.scheduledDate':'Scheduled date','history.publishedDate':'Published date',
  'settings.title':'Settings','settings.subtitle':'Customize reminders and application behavior.','settings.language':'Language','settings.languageHint':'Applied immediately throughout the application.','settings.reminderLead':'Default reminder delay (minutes before publication)','settings.reminderHint':'Used when no custom reminder is set for a publication.','settings.notifications':'Enable notifications','settings.preReminder':'Send a reminder before the scheduled time','settings.launchMinimized':'Start minimized to the taskbar','settings.startOnLogin':'Start with the system','settings.saved':'Saved ✓','settings.save':'Save settings','settings.updates':'Updates','settings.installedVersion':'Installed version: {{version}}','settings.checkUpdate':'Check for updates','settings.devUnavailable':'Update checks are unavailable in development mode (an installed version is required).','settings.checking':'Checking…','settings.upToDate':'TikTok Manager is up to date.','settings.available':'Version {{version}} is available on GitHub.','settings.downloading':'Downloading…','settings.ready':'Version {{version}} is ready. Restart required to install.','settings.updateError':'Error while checking for updates.',
  'planning.titleNew':'New publication','planning.titleEdit':'Edit publication','planning.subtitle':'Import a video, complete the details and schedule the publication date.','planning.noAccount':'Create an account on the “Accounts” page before scheduling a publication.','planning.goAccounts':'Go to accounts','planning.video':'Video','planning.noVideo':'No video','planning.import':'Import a video','planning.changeVideo':'Change video','planning.importing':'Importing…','planning.ready':'✓ Video ready to publish','planning.checks':'⚠ Recommended checks','planning.contentType':'Content type','planning.account':'Account','planning.title':'Title','planning.titlePlaceholder':'Video title','planning.description':'Description / caption','planning.descriptionPlaceholder':'Describe your content…','planning.assistant':'Local editorial assistant','planning.suggestHashtags':'+ Suggested hashtags','planning.hashtags':'Hashtags','planning.date':'Publication date','planning.time':'Publication time','planning.customReminder':'Custom reminder (minutes before, optional)','planning.reminderPlaceholder':'Use the default delay from settings','planning.cancelPublication':'Cancel publication','planning.selectAccount':'Select an account.','planning.importRequired':'Import a video.','planning.titleRequired':'The title is required.','planning.suggestion1':'Did you know? {{title}} — watch until the end 👀','planning.suggestion2':'{{title}}: 3 key points. The last one is the most important.','planning.suggestion3':'I tested {{title}} for you. Here is the honest result.','planning.suggestionFallback':'Here is a tip','planning.suggestionContent':'New content','planning.suggestionMethod':'this method',
  'preview.title':'Publication preview','preview.videoUnavailable':'Video unavailable','preview.unknownAccount':'Unknown account','preview.description':'Description','preview.noDescription':'No description.','preview.publish':'Publish on TikTok','preview.markPublished':'Mark as published','preview.cancel':'Cancel publication','tag.placeholder':'Add a hashtag and press Enter','tag.remove':'Remove {{tag}}','thumbnail.unavailable':'Thumbnail unavailable',
  'status.scheduled':'Scheduled','status.reminderSent':'Reminder sent','status.published':'Published','status.missed':'Missed','status.cancelled':'Cancelled','type.video':'Video','type.story':'Story',
  'about.title':'About TikTok Manager','about.version':'Version {{version}}','about.description':'TikTok Manager helps organize and schedule videos and stories for multiple TikTok accounts from a visual calendar.','about.credits':'Credits','about.design':'Design and development: bob59','about.builtWith':'Built with Electron, React and TypeScript.','about.footer':'Created by bob59 · © 2026',
  'feedback.title':'Suggestion / Correction','feedback.subtitle':'Have an idea or a problem? Write to us.','feedback.subject':'Subject','feedback.message':'Message','feedback.defaultSubject':'TikTok Manager - Suggestion / Correction','feedback.placeholder':'Describe your suggestion or the steps that caused the problem…','feedback.copied':'Address and message copied.','feedback.app':'Application: TikTok Manager','feedback.to':'To',
  'update.title':'Update available','update.versions':'Version {{available}} — you are using {{current}}','update.downloading':'Downloading…','update.calculating':'calculating…','update.remaining':'Estimated time remaining: {{seconds}} s','update.bannerAvailable':'Update {{version}} available','update.bannerReady':'Update {{version}} ready to install','update.details':'View details',
  'menu.file':'File','menu.quit':'Quit','menu.edit':'Edit','menu.undo':'Undo','menu.redo':'Redo','menu.cut':'Cut','menu.copy':'Copy','menu.paste':'Paste','menu.delete':'Delete','menu.selectAll':'Select all','menu.view':'View','menu.reload':'Reload','menu.forceReload':'Force reload','menu.devTools':'Developer tools','menu.actualSize':'Actual size','menu.zoomIn':'Zoom in','menu.zoomOut':'Zoom out','menu.fullscreen':'Full screen','menu.window':'Window','menu.minimize':'Minimize','menu.close':'Close','menu.help':'Help','menu.checkUpdate':'Check for updates','tray.open':'Open TikTok Manager','tray.newPublication':'New publication',
  'notification.reminderTitle':'Publication reminder','notification.reminderBody':'“{{title}}” is scheduled in {{minutes}} min.','notification.dueTitle':'Time to publish!','notification.dueBody':'“{{title}}” is scheduled now.','dialog.importVideo':'Import a video','dialog.videos':'Videos',
  'validation.required':'{{label}} is required.','validation.tooLong':'{{label}} exceeds {{max}} characters.','validation.invalid':'Invalid {{label}}.','validation.managedFile':'{{label}} must be a file imported by the application.','validation.name':'Name','validation.handle':'TikTok username','validation.color':'Color','validation.contentType':'Content type','validation.publicationDate':'Publication date','validation.hashtags':'Hashtag list','validation.reminder':'The reminder must be between 0 and 10,080 minutes.','validation.video':'Video','validation.thumbnail':'Thumbnail','validation.description':'Description','validation.title':'Title','validation.settings':'Invalid settings.','validation.defaultReminder':'Invalid reminder delay.','validation.boolean':'Invalid boolean setting.','validation.filters':'Invalid filters.','validation.filterDate':'Invalid filter date.','validation.id':'Invalid identifier.','validation.dateRange':'Invalid date range.','validation.accountMissing':'Account not found.','validation.publicationMissing':'Publication not found.','validation.duplicate':'A publication is already scheduled for this account at this date and time.','validation.duplicateOther':'Another publication already uses this time slot for this account.','validation.fileTooLarge':'The video exceeds the 4 GB safety limit.','video.warningVertical':'The video is not vertical (9:16 recommended).','video.warningResolution':'Low resolution: 1080 × 1920 is recommended.','video.warningDuration':'The video is longer than 10 minutes.','video.warningAudio':'No audio track detected.','video.warningSize':'The file exceeds 4 GB.','update.devError':'Update checks are unavailable in development mode.','validation.language':'Invalid language.','protocol.invalidPath':'Invalid path','protocol.denied':'Access denied','store.invalid':'Invalid data format.','store.accountsInvalid':'Invalid account list.','store.publicationsInvalid':'Invalid publication list.','store.settingsInvalid':'Invalid settings.'
});

Object.assign(es, en, {
  'language.system':'Idioma del sistema','common.cancel':'Cancelar','common.save':'Guardar','common.saving':'Guardando…','common.close':'Cerrar','common.delete':'Eliminar','common.edit':'Editar','common.loading':'Cargando…','common.confirm':'Confirmar','common.back':'Volver','common.send':'Enviar','common.copy':'Copiar','common.download':'Descargar','common.installRestart':'Instalar y reiniciar','common.later':'Más tarde',
  'nav.calendar':'Calendario','nav.newPublication':'Nueva publicación','nav.accounts':'Cuentas','nav.history':'Historial','nav.settings':'Ajustes','nav.feedback':'Sugerencia / Corrección','nav.about':'Acerca de','calendar.title':'Calendario','calendar.subtitle':'Resumen de tus publicaciones programadas.','calendar.previous':'Anterior','calendar.next':'Siguiente','calendar.today':'Hoy','calendar.month':'Mes','calendar.week':'Semana','calendar.weekOf':'Semana del {{date}}',
  'accounts.title':'Cuentas','accounts.subtitle':'Gestiona tus perfiles de TikTok para organizar tus publicaciones.','accounts.new':'Nueva cuenta','accounts.loading':'Cargando cuentas…','accounts.empty':'Todavía no hay cuentas. Crea la primera para empezar a programar.','accounts.editTitle':'Editar cuenta','accounts.newTitle':'Nueva cuenta','accounts.name':'Nombre de la cuenta','accounts.color':'Color','accounts.required':'El nombre y el usuario de TikTok son obligatorios.','accounts.deleteTitle':'Eliminar cuenta','accounts.deleteConfirm':'¿Seguro que quieres eliminar la cuenta «{{name}}»?',
  'history.title':'Historial','history.subtitle':'Consulta todas tus publicaciones anteriores.','history.allAccounts':'Todas las cuentas','history.status':'Estado','history.defaultStatuses':'Publicada / Perdida / Cancelada','history.from':'Desde','history.to':'Hasta','history.empty':'Ninguna publicación coincide con estos filtros.','history.titleColumn':'Título','history.type':'Tipo','history.scheduledDate':'Fecha programada','history.publishedDate':'Fecha de publicación',
  'settings.title':'Ajustes','settings.subtitle':'Personaliza los recordatorios y el comportamiento de la aplicación.','settings.language':'Idioma','settings.languageHint':'Se aplica inmediatamente a toda la aplicación.','settings.reminderLead':'Antelación predeterminada del recordatorio (minutos)','settings.notifications':'Activar notificaciones','settings.preReminder':'Enviar un recordatorio antes de la hora programada','settings.launchMinimized':'Iniciar minimizado','settings.startOnLogin':'Iniciar con el sistema','settings.saved':'Guardado ✓','settings.save':'Guardar ajustes','settings.updates':'Actualizaciones','settings.installedVersion':'Versión instalada: {{version}}','settings.checkUpdate':'Buscar actualizaciones','settings.checking':'Buscando…','settings.upToDate':'TikTok Manager está actualizado.','settings.available':'La versión {{version}} está disponible en GitHub.','settings.downloading':'Descargando…','settings.ready':'La versión {{version}} está lista. Reinicia para instalarla.',
  'planning.titleNew':'Nueva publicación','planning.titleEdit':'Editar publicación','planning.subtitle':'Importa un vídeo, completa la información y programa la fecha.','planning.noAccount':'Crea una cuenta en la página «Cuentas» antes de programar.','planning.goAccounts':'Ir a cuentas','planning.video':'Vídeo','planning.noVideo':'Sin vídeo','planning.import':'Importar vídeo','planning.changeVideo':'Cambiar vídeo','planning.importing':'Importando…','planning.ready':'✓ Vídeo listo para publicar','planning.checks':'⚠ Comprobaciones recomendadas','planning.contentType':'Tipo de contenido','planning.account':'Cuenta','planning.title':'Título','planning.titlePlaceholder':'Título del vídeo','planning.description':'Descripción / texto','planning.descriptionPlaceholder':'Describe tu contenido…','planning.assistant':'Asistente editorial local','planning.suggestHashtags':'+ Hashtags sugeridos','planning.hashtags':'Hashtags','planning.date':'Fecha de publicación','planning.time':'Hora de publicación','planning.customReminder':'Recordatorio personalizado (minutos antes, opcional)','planning.cancelPublication':'Cancelar publicación','planning.selectAccount':'Selecciona una cuenta.','planning.importRequired':'Importa un vídeo.','planning.titleRequired':'El título es obligatorio.',
  'preview.title':'Vista previa','preview.videoUnavailable':'Vídeo no disponible','preview.unknownAccount':'Cuenta desconocida','preview.description':'Descripción','preview.noDescription':'Sin descripción.','preview.publish':'Publicar en TikTok','preview.markPublished':'Marcar como publicada','preview.cancel':'Cancelar publicación','tag.placeholder':'Añade un hashtag y pulsa Intro','tag.remove':'Quitar {{tag}}','thumbnail.unavailable':'Miniatura no disponible','status.scheduled':'Programada','status.reminderSent':'Recordatorio enviado','status.published':'Publicada','status.missed':'Perdida','status.cancelled':'Cancelada','type.video':'Vídeo','type.story':'Historia',
  'about.title':'Acerca de TikTok Manager','about.version':'Versión {{version}}','about.description':'TikTok Manager permite organizar y programar vídeos e historias de varias cuentas desde un calendario visual.','about.credits':'Créditos','about.design':'Diseño y desarrollo: bob59','about.builtWith':'Creado con Electron, React y TypeScript.','about.footer':'Creado por bob59 · © 2026','feedback.subtitle':'¿Tienes una idea o un problema? Escríbenos.','feedback.subject':'Asunto','feedback.message':'Mensaje','feedback.placeholder':'Describe tu sugerencia o los pasos del problema…','feedback.copied':'Dirección y mensaje copiados.','update.title':'Actualización disponible','update.downloading':'Descargando…','update.details':'Ver detalles','menu.file':'Archivo','menu.quit':'Salir','menu.edit':'Editar','menu.help':'Ayuda','menu.checkUpdate':'Buscar actualizaciones','tray.open':'Abrir TikTok Manager','tray.newPublication':'Nueva publicación','notification.reminderTitle':'Recordatorio de publicación','notification.reminderBody':'«{{title}}» está programada dentro de {{minutes}} min.','notification.dueTitle':'¡Es hora de publicar!','notification.dueBody':'«{{title}}» está programada ahora.','dialog.importVideo':'Importar vídeo','dialog.videos':'Vídeos'
});

Object.assign(de, en, {
  'language.system':'Systemsprache','common.cancel':'Abbrechen','common.save':'Speichern','common.saving':'Speichern…','common.close':'Schließen','common.delete':'Löschen','common.edit':'Bearbeiten','common.loading':'Laden…','common.confirm':'Bestätigen','common.back':'Zurück','common.send':'Senden','common.copy':'Kopieren','common.download':'Herunterladen','common.installRestart':'Installieren und neu starten','common.later':'Später','nav.calendar':'Kalender','nav.newPublication':'Neue Veröffentlichung','nav.accounts':'Konten','nav.history':'Verlauf','nav.settings':'Einstellungen','nav.feedback':'Vorschlag / Korrektur','nav.about':'Über','calendar.title':'Kalender','calendar.subtitle':'Übersicht Ihrer geplanten Veröffentlichungen.','calendar.previous':'Zurück','calendar.next':'Weiter','calendar.today':'Heute','calendar.month':'Monat','calendar.week':'Woche','calendar.weekOf':'Woche vom {{date}}',
  'accounts.title':'Konten','accounts.subtitle':'Verwalten Sie Ihre TikTok-Profile und Veröffentlichungen.','accounts.new':'Neues Konto','accounts.loading':'Konten werden geladen…','accounts.empty':'Noch keine Konten. Erstellen Sie Ihr erstes Konto.','accounts.editTitle':'Konto bearbeiten','accounts.newTitle':'Neues Konto','accounts.name':'Kontoname','accounts.color':'Farbe','accounts.required':'Name und TikTok-Benutzername sind erforderlich.','accounts.deleteTitle':'Konto löschen','accounts.deleteConfirm':'Möchten Sie das Konto „{{name}}“ wirklich löschen?','history.title':'Verlauf','history.subtitle':'Alle vergangenen Veröffentlichungen anzeigen.','history.allAccounts':'Alle Konten','history.status':'Status','history.from':'Von','history.to':'Bis','history.empty':'Keine Veröffentlichung entspricht diesen Filtern.','history.titleColumn':'Titel','history.type':'Typ','history.scheduledDate':'Geplantes Datum','history.publishedDate':'Veröffentlichungsdatum',
  'settings.title':'Einstellungen','settings.subtitle':'Erinnerungen und App-Verhalten anpassen.','settings.language':'Sprache','settings.languageHint':'Wird sofort in der gesamten Anwendung angewendet.','settings.notifications':'Benachrichtigungen aktivieren','settings.preReminder':'Vor der geplanten Zeit erinnern','settings.launchMinimized':'Minimiert starten','settings.startOnLogin':'Mit dem System starten','settings.saved':'Gespeichert ✓','settings.save':'Einstellungen speichern','settings.updates':'Updates','settings.installedVersion':'Installierte Version: {{version}}','settings.checkUpdate':'Nach Updates suchen','settings.checking':'Suche läuft…','settings.upToDate':'TikTok Manager ist aktuell.','settings.downloading':'Download läuft…',
  'planning.titleNew':'Neue Veröffentlichung','planning.titleEdit':'Veröffentlichung bearbeiten','planning.subtitle':'Video importieren, Angaben ausfüllen und Datum planen.','planning.noAccount':'Erstellen Sie zuerst ein Konto.','planning.goAccounts':'Zu den Konten','planning.video':'Video','planning.noVideo':'Kein Video','planning.import':'Video importieren','planning.changeVideo':'Video ändern','planning.importing':'Import läuft…','planning.ready':'✓ Video bereit','planning.checks':'⚠ Empfohlene Prüfungen','planning.contentType':'Inhaltstyp','planning.account':'Konto','planning.title':'Titel','planning.description':'Beschreibung / Text','planning.assistant':'Lokaler Redaktionsassistent','planning.hashtags':'Hashtags','planning.date':'Veröffentlichungsdatum','planning.time':'Veröffentlichungszeit','planning.cancelPublication':'Veröffentlichung abbrechen','planning.selectAccount':'Wählen Sie ein Konto.','planning.importRequired':'Importieren Sie ein Video.','planning.titleRequired':'Der Titel ist erforderlich.','preview.title':'Vorschau','preview.videoUnavailable':'Video nicht verfügbar','preview.unknownAccount':'Unbekanntes Konto','preview.description':'Beschreibung','preview.noDescription':'Keine Beschreibung.','preview.publish':'Auf TikTok veröffentlichen','preview.markPublished':'Als veröffentlicht markieren','preview.cancel':'Veröffentlichung abbrechen','status.scheduled':'Geplant','status.reminderSent':'Erinnerung gesendet','status.published':'Veröffentlicht','status.missed':'Verpasst','status.cancelled':'Abgebrochen','type.video':'Video','type.story':'Story','about.title':'Über TikTok Manager','about.credits':'Mitwirkende','feedback.subject':'Betreff','feedback.message':'Nachricht','feedback.copied':'Adresse und Nachricht kopiert.','update.title':'Update verfügbar','update.details':'Details anzeigen','menu.file':'Datei','menu.quit':'Beenden','menu.help':'Hilfe','menu.checkUpdate':'Nach Updates suchen','tray.open':'TikTok Manager öffnen','notification.reminderTitle':'Veröffentlichungserinnerung','notification.dueTitle':'Zeit zum Veröffentlichen!','dialog.importVideo':'Video importieren','dialog.videos':'Videos'
});

Object.assign(it, en, {
  'language.system':'Lingua di sistema','common.cancel':'Annulla','common.save':'Salva','common.saving':'Salvataggio…','common.close':'Chiudi','common.delete':'Elimina','common.edit':'Modifica','common.loading':'Caricamento…','common.confirm':'Conferma','common.back':'Indietro','common.send':'Invia','common.copy':'Copia','common.download':'Scarica','common.installRestart':'Installa e riavvia','common.later':'Più tardi','nav.calendar':'Calendario','nav.newPublication':'Nuova pubblicazione','nav.accounts':'Account','nav.history':'Cronologia','nav.settings':'Impostazioni','nav.feedback':'Suggerimento / Correzione','nav.about':'Informazioni','calendar.title':'Calendario','calendar.subtitle':'Panoramica delle pubblicazioni programmate.','calendar.previous':'Precedente','calendar.next':'Successivo','calendar.today':'Oggi','calendar.month':'Mese','calendar.week':'Settimana','calendar.weekOf':'Settimana del {{date}}',
  'accounts.title':'Account','accounts.subtitle':'Gestisci i profili TikTok e le pubblicazioni.','accounts.new':'Nuovo account','accounts.loading':'Caricamento account…','accounts.empty':'Nessun account. Crea il primo per iniziare.','accounts.editTitle':'Modifica account','accounts.newTitle':'Nuovo account','accounts.name':'Nome account','accounts.color':'Colore','accounts.required':'Nome e username TikTok sono obbligatori.','accounts.deleteTitle':'Elimina account','accounts.deleteConfirm':'Vuoi davvero eliminare l’account «{{name}}»?','history.title':'Cronologia','history.subtitle':'Consulta tutte le pubblicazioni passate.','history.allAccounts':'Tutti gli account','history.status':'Stato','history.from':'Da','history.to':'A','history.empty':'Nessuna pubblicazione corrisponde ai filtri.','history.titleColumn':'Titolo','history.type':'Tipo','history.scheduledDate':'Data programmata','history.publishedDate':'Data pubblicazione',
  'settings.title':'Impostazioni','settings.subtitle':'Personalizza promemoria e comportamento.','settings.language':'Lingua','settings.languageHint':'Applicata immediatamente a tutta l’applicazione.','settings.notifications':'Attiva notifiche','settings.preReminder':'Invia un promemoria prima dell’orario','settings.launchMinimized':'Avvia ridotto a icona','settings.startOnLogin':'Avvia con il sistema','settings.saved':'Salvato ✓','settings.save':'Salva impostazioni','settings.updates':'Aggiornamenti','settings.installedVersion':'Versione installata: {{version}}','settings.checkUpdate':'Cerca aggiornamenti','settings.checking':'Ricerca in corso…','settings.upToDate':'TikTok Manager è aggiornato.','settings.downloading':'Download in corso…',
  'planning.titleNew':'Nuova pubblicazione','planning.titleEdit':'Modifica pubblicazione','planning.subtitle':'Importa un video, completa i dati e programma la data.','planning.noAccount':'Crea prima un account.','planning.goAccounts':'Vai agli account','planning.video':'Video','planning.noVideo':'Nessun video','planning.import':'Importa video','planning.changeVideo':'Cambia video','planning.importing':'Importazione…','planning.ready':'✓ Video pronto','planning.checks':'⚠ Controlli consigliati','planning.contentType':'Tipo di contenuto','planning.account':'Account','planning.title':'Titolo','planning.description':'Descrizione / didascalia','planning.assistant':'Assistente editoriale locale','planning.hashtags':'Hashtag','planning.date':'Data di pubblicazione','planning.time':'Ora di pubblicazione','planning.cancelPublication':'Annulla pubblicazione','planning.selectAccount':'Seleziona un account.','planning.importRequired':'Importa un video.','planning.titleRequired':'Il titolo è obbligatorio.','preview.title':'Anteprima','preview.videoUnavailable':'Video non disponibile','preview.unknownAccount':'Account sconosciuto','preview.description':'Descrizione','preview.noDescription':'Nessuna descrizione.','preview.publish':'Pubblica su TikTok','preview.markPublished':'Segna come pubblicato','preview.cancel':'Annulla pubblicazione','status.scheduled':'Programmato','status.reminderSent':'Promemoria inviato','status.published':'Pubblicato','status.missed':'Mancato','status.cancelled':'Annullato','type.video':'Video','type.story':'Storia','about.title':'Informazioni su TikTok Manager','about.credits':'Crediti','feedback.subject':'Oggetto','feedback.message':'Messaggio','feedback.copied':'Indirizzo e messaggio copiati.','update.title':'Aggiornamento disponibile','update.details':'Vedi dettagli','menu.file':'File','menu.quit':'Esci','menu.help':'Aiuto','menu.checkUpdate':'Cerca aggiornamenti','tray.open':'Apri TikTok Manager','notification.reminderTitle':'Promemoria pubblicazione','notification.dueTitle':'È ora di pubblicare!','dialog.importVideo':'Importa video','dialog.videos':'Video'
});

Object.assign(es, {
  'accounts.namePlaceholder':'Ej. Cuenta principal','accounts.handle':'Usuario de TikTok','accounts.handlePlaceholder':'@miusuario','accounts.chooseColor':'Elegir el color {{color}}','accounts.count':'{{count}} publicación(es)','accounts.deleteWithPublications':'Esta cuenta tiene {{count}} publicación(es) asociada(s). También se eliminarán. ¿Continuar?','settings.reminderHint':'Se usa cuando una publicación no tiene un recordatorio personalizado.','settings.devUnavailable':'La búsqueda no está disponible en modo desarrollo (se necesita una versión instalada).','settings.updateError':'Error al buscar actualizaciones.','planning.reminderPlaceholder':'Usar la antelación predeterminada de los ajustes','planning.suggestion1':'¿Lo sabías? {{title}} — mira hasta el final 👀','planning.suggestion2':'{{title}}: 3 puntos clave. El último es el más importante.','planning.suggestion3':'He probado {{title}} por ti. Este es el resultado sin rodeos.','planning.suggestionFallback':'Aquí tienes un consejo','planning.suggestionContent':'Nuevo contenido','planning.suggestionMethod':'este método',
  'feedback.defaultSubject':'TikTok Manager - Sugerencia / Corrección','feedback.app':'Aplicación: TikTok Manager','feedback.to':'Para','update.versions':'Versión {{available}} — estás usando la {{current}}','update.calculating':'calculando…','update.remaining':'Tiempo restante estimado: {{seconds}} s','update.bannerAvailable':'Actualización {{version}} disponible','update.bannerReady':'Actualización {{version}} lista para instalar','menu.undo':'Deshacer','menu.redo':'Rehacer','menu.cut':'Cortar','menu.copy':'Copiar','menu.paste':'Pegar','menu.delete':'Eliminar','menu.selectAll':'Seleccionar todo','menu.view':'Ver','menu.reload':'Recargar','menu.forceReload':'Forzar recarga','menu.devTools':'Herramientas de desarrollo','menu.actualSize':'Tamaño real','menu.zoomIn':'Acercar','menu.zoomOut':'Alejar','menu.fullscreen':'Pantalla completa','menu.window':'Ventana','menu.minimize':'Minimizar','menu.close':'Cerrar',
  'validation.required':'{{label}} es obligatorio.','validation.tooLong':'{{label}} supera los {{max}} caracteres.','validation.invalid':'{{label}} no es válido.','validation.managedFile':'{{label}} debe ser un archivo importado por la aplicación.','validation.name':'El nombre','validation.handle':'El usuario de TikTok','validation.color':'Color','validation.contentType':'Tipo de contenido','validation.publicationDate':'Fecha de publicación','validation.hashtags':'Lista de hashtags','validation.reminder':'El recordatorio debe estar entre 0 y 10.080 minutos.','validation.video':'Vídeo','validation.thumbnail':'Miniatura','validation.description':'Descripción','validation.title':'El título','validation.settings':'Ajustes no válidos.','validation.defaultReminder':'Antelación del recordatorio no válida.','validation.boolean':'Ajuste booleano no válido.','validation.filters':'Filtros no válidos.','validation.filterDate':'Fecha de filtro no válida.','validation.id':'Identificador no válido.','validation.dateRange':'Intervalo de fechas no válido.','validation.accountMissing':'Cuenta no encontrada.','validation.publicationMissing':'Publicación no encontrada.','validation.duplicate':'Ya hay una publicación programada para esta cuenta en esa fecha y hora.','validation.duplicateOther':'Otra publicación ya usa esta franja para la cuenta.','validation.fileTooLarge':'El vídeo supera el límite de seguridad de 4 GB.','video.warningVertical':'El vídeo no es vertical (se recomienda 9:16).','video.warningResolution':'Resolución baja: se recomienda 1080 × 1920.','video.warningDuration':'El vídeo dura más de 10 minutos.','video.warningAudio':'No se detectó ninguna pista de audio.','video.warningSize':'El archivo supera los 4 GB.','update.devError':'La búsqueda no está disponible en modo desarrollo.','validation.language':'Idioma no válido.','protocol.invalidPath':'Ruta no válida','protocol.denied':'Acceso denegado','store.invalid':'Formato de datos no válido.','store.accountsInvalid':'Lista de cuentas no válida.','store.publicationsInvalid':'Lista de publicaciones no válida.','store.settingsInvalid':'Ajustes no válidos.'
});

Object.assign(de, {
  'accounts.namePlaceholder':'Z. B. Hauptkonto','accounts.handle':'TikTok-Benutzername','accounts.handlePlaceholder':'@meinname','accounts.chooseColor':'Farbe {{color}} auswählen','accounts.count':'{{count}} Veröffentlichung(en)','accounts.deleteWithPublications':'Dieses Konto hat {{count}} zugeordnete Veröffentlichung(en). Sie werden ebenfalls gelöscht. Fortfahren?','history.defaultStatuses':'Veröffentlicht / Verpasst / Abgebrochen','settings.reminderLead':'Standard-Erinnerung (Minuten vor Veröffentlichung)','settings.reminderHint':'Wird verwendet, wenn keine eigene Erinnerung festgelegt ist.','settings.devUnavailable':'Die Suche ist im Entwicklungsmodus nicht verfügbar (installierte Version erforderlich).','settings.available':'Version {{version}} ist auf GitHub verfügbar.','settings.ready':'Version {{version}} ist bereit. Für die Installation ist ein Neustart erforderlich.','settings.updateError':'Fehler bei der Update-Suche.','planning.titlePlaceholder':'Videotitel','planning.descriptionPlaceholder':'Beschreiben Sie Ihren Inhalt…','planning.suggestHashtags':'+ Vorgeschlagene Hashtags','planning.customReminder':'Eigene Erinnerung (Minuten vorher, optional)','planning.reminderPlaceholder':'Standardwert aus den Einstellungen verwenden','planning.suggestion1':'Schon gewusst? {{title}} — bis zum Ende ansehen 👀','planning.suggestion2':'{{title}}: 3 wichtige Punkte. Der letzte ist am wichtigsten.','planning.suggestion3':'Ich habe {{title}} getestet. Hier ist das ehrliche Ergebnis.','planning.suggestionFallback':'Hier ist ein Tipp','planning.suggestionContent':'Neuer Inhalt','planning.suggestionMethod':'diese Methode','tag.placeholder':'Hashtag hinzufügen und Eingabetaste drücken','tag.remove':'{{tag}} entfernen','thumbnail.unavailable':'Vorschaubild nicht verfügbar',
  'about.description':'TikTok Manager organisiert und plant Videos und Storys für mehrere TikTok-Konten in einem visuellen Kalender.','about.design':'Konzeption und Entwicklung: bob59','about.builtWith':'Erstellt mit Electron, React und TypeScript.','about.footer':'Erstellt von bob59 · © 2026','feedback.subtitle':'Eine Idee oder ein Problem? Schreiben Sie uns.','feedback.defaultSubject':'TikTok Manager - Vorschlag / Korrektur','feedback.placeholder':'Beschreiben Sie Ihren Vorschlag oder die Schritte zum Problem…','feedback.app':'Anwendung: TikTok Manager','feedback.to':'An','update.versions':'Version {{available}} — installiert ist {{current}}','update.downloading':'Download läuft…','update.calculating':'Berechnung…','update.remaining':'Geschätzte Restzeit: {{seconds}} s','update.bannerAvailable':'Update {{version}} verfügbar','update.bannerReady':'Update {{version}} installationsbereit','menu.undo':'Rückgängig','menu.redo':'Wiederholen','menu.cut':'Ausschneiden','menu.copy':'Kopieren','menu.paste':'Einfügen','menu.delete':'Löschen','menu.selectAll':'Alles auswählen','menu.view':'Ansicht','menu.reload':'Neu laden','menu.forceReload':'Neuladen erzwingen','menu.devTools':'Entwicklerwerkzeuge','menu.actualSize':'Tatsächliche Größe','menu.zoomIn':'Vergrößern','menu.zoomOut':'Verkleinern','menu.fullscreen':'Vollbild','menu.window':'Fenster','menu.minimize':'Minimieren','menu.close':'Schließen','tray.newPublication':'Neue Veröffentlichung','notification.reminderBody':'„{{title}}“ ist in {{minutes}} Min. geplant.','notification.dueBody':'„{{title}}“ ist jetzt geplant.',
  'validation.required':'{{label}} ist erforderlich.','validation.tooLong':'{{label}} überschreitet {{max}} Zeichen.','validation.invalid':'{{label}} ist ungültig.','validation.managedFile':'{{label}} muss eine von der Anwendung importierte Datei sein.','validation.name':'Name','validation.handle':'TikTok-Benutzername','validation.color':'Farbe','validation.contentType':'Inhaltstyp','validation.publicationDate':'Veröffentlichungsdatum','validation.hashtags':'Hashtag-Liste','validation.reminder':'Die Erinnerung muss zwischen 0 und 10.080 Minuten liegen.','validation.video':'Video','validation.thumbnail':'Vorschaubild','validation.description':'Beschreibung','validation.title':'Titel','validation.settings':'Ungültige Einstellungen.','validation.defaultReminder':'Ungültige Erinnerungszeit.','validation.boolean':'Ungültige boolesche Einstellung.','validation.filters':'Ungültige Filter.','validation.filterDate':'Ungültiges Filterdatum.','validation.id':'Ungültige Kennung.','validation.dateRange':'Ungültiger Datumsbereich.','validation.accountMissing':'Konto nicht gefunden.','validation.publicationMissing':'Veröffentlichung nicht gefunden.','validation.duplicate':'Für dieses Konto ist zu diesem Zeitpunkt bereits eine Veröffentlichung geplant.','validation.duplicateOther':'Eine andere Veröffentlichung belegt diesen Zeitpunkt bereits.','validation.fileTooLarge':'Das Video überschreitet die Sicherheitsgrenze von 4 GB.','video.warningVertical':'Das Video ist nicht vertikal (9:16 empfohlen).','video.warningResolution':'Niedrige Auflösung: 1080 × 1920 empfohlen.','video.warningDuration':'Das Video ist länger als 10 Minuten.','video.warningAudio':'Keine Audiospur erkannt.','video.warningSize':'Die Datei überschreitet 4 GB.','update.devError':'Update-Suche im Entwicklungsmodus nicht verfügbar.','validation.language':'Ungültige Sprache.','protocol.invalidPath':'Ungültiger Pfad','protocol.denied':'Zugriff verweigert','store.invalid':'Ungültiges Datenformat.','store.accountsInvalid':'Ungültige Kontoliste.','store.publicationsInvalid':'Ungültige Veröffentlichungsliste.','store.settingsInvalid':'Ungültige Einstellungen.'
});

Object.assign(it, {
  'accounts.namePlaceholder':'Es. Account principale','accounts.handle':'Nome utente TikTok','accounts.handlePlaceholder':'@mionome','accounts.chooseColor':'Scegli il colore {{color}}','accounts.count':'{{count}} pubblicazione(i)','accounts.deleteWithPublications':'Questo account ha {{count}} pubblicazione(i) associata(e). Verranno eliminate. Continuare?','history.defaultStatuses':'Pubblicato / Mancato / Annullato','settings.reminderLead':'Anticipo predefinito del promemoria (minuti)','settings.reminderHint':'Usato quando non è impostato un promemoria personalizzato.','settings.devUnavailable':'Ricerca non disponibile in modalità sviluppo (serve una versione installata).','settings.available':'La versione {{version}} è disponibile su GitHub.','settings.ready':'La versione {{version}} è pronta. Riavvia per installarla.','settings.updateError':'Errore durante la ricerca degli aggiornamenti.','planning.titlePlaceholder':'Titolo del video','planning.descriptionPlaceholder':'Descrivi il contenuto…','planning.suggestHashtags':'+ Hashtag suggeriti','planning.customReminder':'Promemoria personalizzato (minuti prima, opzionale)','planning.reminderPlaceholder':'Usa l’anticipo predefinito delle impostazioni','planning.suggestion1':'Lo sapevi? {{title}} — guarda fino alla fine 👀','planning.suggestion2':'{{title}}: 3 punti chiave. L’ultimo è il più importante.','planning.suggestion3':'Ho provato {{title}} per te. Ecco il risultato senza filtri.','planning.suggestionFallback':'Ecco un consiglio','planning.suggestionContent':'Nuovo contenuto','planning.suggestionMethod':'questo metodo','tag.placeholder':'Aggiungi un hashtag e premi Invio','tag.remove':'Rimuovi {{tag}}','thumbnail.unavailable':'Miniatura non disponibile',
  'about.description':'TikTok Manager organizza e programma video e storie di più account da un calendario visivo.','about.design':'Progettazione e sviluppo: bob59','about.builtWith':'Creato con Electron, React e TypeScript.','about.footer':'Creato da bob59 · © 2026','feedback.subtitle':'Hai un’idea o un problema? Scrivici.','feedback.defaultSubject':'TikTok Manager - Suggerimento / Correzione','feedback.placeholder':'Descrivi il suggerimento o i passaggi del problema…','feedback.app':'Applicazione: TikTok Manager','feedback.to':'A','update.versions':'Versione {{available}} — stai usando la {{current}}','update.downloading':'Download in corso…','update.calculating':'calcolo…','update.remaining':'Tempo rimanente stimato: {{seconds}} s','update.bannerAvailable':'Aggiornamento {{version}} disponibile','update.bannerReady':'Aggiornamento {{version}} pronto da installare','menu.undo':'Annulla','menu.redo':'Ripeti','menu.cut':'Taglia','menu.copy':'Copia','menu.paste':'Incolla','menu.delete':'Elimina','menu.selectAll':'Seleziona tutto','menu.view':'Visualizza','menu.reload':'Ricarica','menu.forceReload':'Forza ricaricamento','menu.devTools':'Strumenti di sviluppo','menu.actualSize':'Dimensioni reali','menu.zoomIn':'Ingrandisci','menu.zoomOut':'Riduci','menu.fullscreen':'Schermo intero','menu.window':'Finestra','menu.minimize':'Riduci a icona','menu.close':'Chiudi','tray.newPublication':'Nuova pubblicazione','notification.reminderBody':'«{{title}}» è programmato tra {{minutes}} min.','notification.dueBody':'«{{title}}» è programmato adesso.',
  'validation.required':'{{label}} è obbligatorio.','validation.tooLong':'{{label}} supera {{max}} caratteri.','validation.invalid':'{{label}} non è valido.','validation.managedFile':'{{label}} deve essere un file importato dall’applicazione.','validation.name':'Il nome','validation.handle':'Il nome utente TikTok','validation.color':'Colore','validation.contentType':'Tipo di contenuto','validation.publicationDate':'Data di pubblicazione','validation.hashtags':'Elenco hashtag','validation.reminder':'Il promemoria deve essere compreso tra 0 e 10.080 minuti.','validation.video':'Video','validation.thumbnail':'Miniatura','validation.description':'Descrizione','validation.title':'Il titolo','validation.settings':'Impostazioni non valide.','validation.defaultReminder':'Anticipo del promemoria non valido.','validation.boolean':'Impostazione booleana non valida.','validation.filters':'Filtri non validi.','validation.filterDate':'Data del filtro non valida.','validation.id':'Identificatore non valido.','validation.dateRange':'Intervallo di date non valido.','validation.accountMissing':'Account non trovato.','validation.publicationMissing':'Pubblicazione non trovata.','validation.duplicate':'Esiste già una pubblicazione programmata per questo account alla stessa data e ora.','validation.duplicateOther':'Un’altra pubblicazione usa già questa fascia oraria.','validation.fileTooLarge':'Il video supera il limite di sicurezza di 4 GB.','video.warningVertical':'Il video non è verticale (consigliato 9:16).','video.warningResolution':'Risoluzione bassa: consigliata 1080 × 1920.','video.warningDuration':'Il video supera i 10 minuti.','video.warningAudio':'Nessuna traccia audio rilevata.','video.warningSize':'Il file supera i 4 GB.','update.devError':'Ricerca non disponibile in modalità sviluppo.','validation.language':'Lingua non valida.','protocol.invalidPath':'Percorso non valido','protocol.denied':'Accesso negato','store.invalid':'Formato dati non valido.','store.accountsInvalid':'Elenco account non valido.','store.publicationsInvalid':'Elenco pubblicazioni non valido.','store.settingsInvalid':'Impostazioni non valide.'
});

Object.assign(en, {
  'welcome.title':'Welcome to TikTok Manager','welcome.eyebrow':'Welcome','welcome.headline':'Thank you for using TikTok Manager!','welcome.description':'Organize your content, schedule publications and manage multiple TikTok accounts from a clear calendar.','welcome.thanks':'Your trust helps us keep improving this free application.','welcome.support':'If TikTok Manager is useful to you, you can support its development through PayPal.','welcome.donate':'Donate','welcome.later':'Later','welcome.dontShow':'Do not show this window at startup','welcome.closeLabel':'Close the welcome window','welcome.openError':'Unable to open the PayPal page.','settings.welcomeTitle':'Welcome and support','settings.welcomeDescription':'Choose whether the welcome window appears at startup.','settings.showWelcome':'Show welcome at startup','settings.previewWelcome':'View the welcome window again','donation.invalidUrl':'The built-in donation link is invalid.'
});
Object.assign(es, {
  'welcome.title':'Bienvenido a TikTok Manager','welcome.eyebrow':'Bienvenido','welcome.headline':'¡Gracias por usar TikTok Manager!','welcome.description':'Organiza tu contenido, programa publicaciones y gestiona varias cuentas desde un calendario claro.','welcome.thanks':'Tu confianza nos ayuda a mejorar esta aplicación gratuita.','welcome.support':'Si TikTok Manager te resulta útil, puedes apoyar su desarrollo mediante PayPal.','welcome.donate':'Hacer una donación','welcome.later':'Más tarde','welcome.dontShow':'No mostrar esta ventana al iniciar','welcome.closeLabel':'Cerrar la ventana de bienvenida','welcome.openError':'No se pudo abrir la página de PayPal.','settings.welcomeTitle':'Bienvenida y apoyo','settings.welcomeDescription':'Elige si la ventana de bienvenida aparece al iniciar.','settings.showWelcome':'Mostrar la bienvenida al iniciar','settings.previewWelcome':'Volver a ver la bienvenida','donation.invalidUrl':'El enlace de donación integrado no es válido.'
});
Object.assign(de, {
  'welcome.title':'Willkommen bei TikTok Manager','welcome.eyebrow':'Willkommen','welcome.headline':'Vielen Dank, dass Sie TikTok Manager verwenden!','welcome.description':'Organisieren Sie Inhalte, planen Sie Veröffentlichungen und verwalten Sie mehrere Konten in einem übersichtlichen Kalender.','welcome.thanks':'Ihr Vertrauen hilft uns, diese kostenlose Anwendung weiterzuentwickeln.','welcome.support':'Wenn TikTok Manager hilfreich ist, können Sie die Entwicklung über PayPal unterstützen.','welcome.donate':'Spenden','welcome.later':'Später','welcome.dontShow':'Dieses Fenster beim Start nicht mehr anzeigen','welcome.closeLabel':'Willkommensfenster schließen','welcome.openError':'Die PayPal-Seite konnte nicht geöffnet werden.','settings.welcomeTitle':'Willkommen und Unterstützung','settings.welcomeDescription':'Legen Sie fest, ob das Willkommensfenster beim Start angezeigt wird.','settings.showWelcome':'Willkommen beim Start anzeigen','settings.previewWelcome':'Willkommensfenster erneut anzeigen','donation.invalidUrl':'Der integrierte Spendenlink ist ungültig.'
});
Object.assign(it, {
  'welcome.title':'Benvenuto in TikTok Manager','welcome.eyebrow':'Benvenuto','welcome.headline':'Grazie per aver scelto TikTok Manager!','welcome.description':'Organizza i contenuti, programma le pubblicazioni e gestisci più account da un calendario chiaro.','welcome.thanks':'La tua fiducia ci aiuta a migliorare questa applicazione gratuita.','welcome.support':'Se TikTok Manager ti è utile, puoi sostenere lo sviluppo tramite PayPal.','welcome.donate':'Fai una donazione','welcome.later':'Più tardi','welcome.dontShow':'Non mostrare questa finestra all’avvio','welcome.closeLabel':'Chiudi la finestra di benvenuto','welcome.openError':'Impossibile aprire la pagina PayPal.','settings.welcomeTitle':'Benvenuto e sostegno','settings.welcomeDescription':'Scegli se mostrare la finestra di benvenuto all’avvio.','settings.showWelcome':'Mostra il benvenuto all’avvio','settings.previewWelcome':'Rivedi la finestra di benvenuto','donation.invalidUrl':'Il link di donazione integrato non è valido.'
});

export const catalogs: Record<SupportedLocale, Catalog> = { fr, en, es, de, it };

export function resolveLocale(preference: LanguagePreference | string | undefined, systemLocale: string): SupportedLocale {
  const requested = preference && preference !== 'system' ? preference : systemLocale;
  const base = requested.toLowerCase().split(/[-_]/)[0];
  return SUPPORTED_LOCALES.includes(base as SupportedLocale) ? base as SupportedLocale : 'en';
}

export function translate(locale: SupportedLocale, key: TranslationKey, values: Record<string, string | number> = {}): string {
  const template = catalogs[locale][key] || catalogs.en[key] || catalogs.fr[key];
  return template.replace(/{{(\w+)}}/g, (_match, name: string) => String(values[name] ?? `{{${name}}}`));
}
